<?php

namespace Informacje\Main\MainBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdministracjaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Informacje\Main\MainBundle\Controller\AdministracjaController();
        return $instance;
    }
}
