<?php

namespace Proxies\__CG__\Informacje\Main\MainBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Strona extends \Informacje\Main\MainBundle\Entity\Strona implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setCzas()
    {
        $this->__load();
        return parent::setCzas();
    }

    public function getCzas()
    {
        $this->__load();
        return parent::getCzas();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setHeader1($header1)
    {
        $this->__load();
        return parent::setHeader1($header1);
    }

    public function getHeader1()
    {
        $this->__load();
        return parent::getHeader1();
    }

    public function setHeader2($header2)
    {
        $this->__load();
        return parent::setHeader2($header2);
    }

    public function getHeader2()
    {
        $this->__load();
        return parent::getHeader2();
    }

    public function setHeader3($header3)
    {
        $this->__load();
        return parent::setHeader3($header3);
    }

    public function getHeader3()
    {
        $this->__load();
        return parent::getHeader3();
    }

    public function setContent($content)
    {
        $this->__load();
        return parent::setContent($content);
    }

    public function getContent()
    {
        $this->__load();
        return parent::getContent();
    }

    public function setRodzaj($rodzaj)
    {
        $this->__load();
        return parent::setRodzaj($rodzaj);
    }

    public function getRodzaj()
    {
        $this->__load();
        return parent::getRodzaj();
    }

    public function setDescription1($description1)
    {
        $this->__load();
        return parent::setDescription1($description1);
    }

    public function getDescription1()
    {
        $this->__load();
        return parent::getDescription1();
    }

    public function setDescription2($description2)
    {
        $this->__load();
        return parent::setDescription2($description2);
    }

    public function getDescription2()
    {
        $this->__load();
        return parent::getDescription2();
    }

    public function setDescription3($description3)
    {
        $this->__load();
        return parent::setDescription3($description3);
    }

    public function getDescription3()
    {
        $this->__load();
        return parent::getDescription3();
    }

    public function setDescription4($description4)
    {
        $this->__load();
        return parent::setDescription4($description4);
    }

    public function getDescription4()
    {
        $this->__load();
        return parent::getDescription4();
    }

    public function setDescription5($description5)
    {
        $this->__load();
        return parent::setDescription5($description5);
    }

    public function getDescription5()
    {
        $this->__load();
        return parent::getDescription5();
    }

    public function setDescription6($description6)
    {
        $this->__load();
        return parent::setDescription6($description6);
    }

    public function getDescription6()
    {
        $this->__load();
        return parent::getDescription6();
    }

    public function setDescription7($description7)
    {
        $this->__load();
        return parent::setDescription7($description7);
    }

    public function getDescription7()
    {
        $this->__load();
        return parent::getDescription7();
    }

    public function setDescription8($description8)
    {
        $this->__load();
        return parent::setDescription8($description8);
    }

    public function getDescription8()
    {
        $this->__load();
        return parent::getDescription8();
    }

    public function setDescription9($description9)
    {
        $this->__load();
        return parent::setDescription9($description9);
    }

    public function getDescription9()
    {
        $this->__load();
        return parent::getDescription9();
    }

    public function setDescription10($description10)
    {
        $this->__load();
        return parent::setDescription10($description10);
    }

    public function getDescription10()
    {
        $this->__load();
        return parent::getDescription10();
    }

    public function getAbsolutePath1()
    {
        $this->__load();
        return parent::getAbsolutePath1();
    }

    public function getWebPath1()
    {
        $this->__load();
        return parent::getWebPath1();
    }

    public function preUpload1()
    {
        $this->__load();
        return parent::preUpload1();
    }

    public function upload1()
    {
        $this->__load();
        return parent::upload1();
    }

    public function removeUpload1()
    {
        $this->__load();
        return parent::removeUpload1();
    }

    public function getAbsolutePath2()
    {
        $this->__load();
        return parent::getAbsolutePath2();
    }

    public function getWebPath2()
    {
        $this->__load();
        return parent::getWebPath2();
    }

    public function preUpload2()
    {
        $this->__load();
        return parent::preUpload2();
    }

    public function upload2()
    {
        $this->__load();
        return parent::upload2();
    }

    public function removeUpload2()
    {
        $this->__load();
        return parent::removeUpload2();
    }

    public function getAbsolutePath3()
    {
        $this->__load();
        return parent::getAbsolutePath3();
    }

    public function getWebPath3()
    {
        $this->__load();
        return parent::getWebPath3();
    }

    public function preUpload3()
    {
        $this->__load();
        return parent::preUpload3();
    }

    public function upload3()
    {
        $this->__load();
        return parent::upload3();
    }

    public function removeUpload3()
    {
        $this->__load();
        return parent::removeUpload3();
    }

    public function getAbsolutePath4()
    {
        $this->__load();
        return parent::getAbsolutePath4();
    }

    public function getWebPath4()
    {
        $this->__load();
        return parent::getWebPath4();
    }

    public function preUpload4()
    {
        $this->__load();
        return parent::preUpload4();
    }

    public function upload4()
    {
        $this->__load();
        return parent::upload4();
    }

    public function removeUpload4()
    {
        $this->__load();
        return parent::removeUpload4();
    }

    public function getAbsolutePath5()
    {
        $this->__load();
        return parent::getAbsolutePath5();
    }

    public function getWebPath5()
    {
        $this->__load();
        return parent::getWebPath5();
    }

    public function preUpload5()
    {
        $this->__load();
        return parent::preUpload5();
    }

    public function upload5()
    {
        $this->__load();
        return parent::upload5();
    }

    public function removeUpload5()
    {
        $this->__load();
        return parent::removeUpload5();
    }

    public function getAbsolutePath6()
    {
        $this->__load();
        return parent::getAbsolutePath6();
    }

    public function getWebPath6()
    {
        $this->__load();
        return parent::getWebPath6();
    }

    public function preUpload6()
    {
        $this->__load();
        return parent::preUpload6();
    }

    public function upload6()
    {
        $this->__load();
        return parent::upload6();
    }

    public function removeUpload6()
    {
        $this->__load();
        return parent::removeUpload6();
    }

    public function getAbsolutePath7()
    {
        $this->__load();
        return parent::getAbsolutePath7();
    }

    public function getWebPath7()
    {
        $this->__load();
        return parent::getWebPath7();
    }

    public function preUpload7()
    {
        $this->__load();
        return parent::preUpload7();
    }

    public function upload7()
    {
        $this->__load();
        return parent::upload7();
    }

    public function removeUpload7()
    {
        $this->__load();
        return parent::removeUpload7();
    }

    public function getAbsolutePath8()
    {
        $this->__load();
        return parent::getAbsolutePath8();
    }

    public function getWebPath8()
    {
        $this->__load();
        return parent::getWebPath8();
    }

    public function preUpload8()
    {
        $this->__load();
        return parent::preUpload8();
    }

    public function upload8()
    {
        $this->__load();
        return parent::upload8();
    }

    public function removeUpload8()
    {
        $this->__load();
        return parent::removeUpload8();
    }

    public function getAbsolutePath9()
    {
        $this->__load();
        return parent::getAbsolutePath9();
    }

    public function getWebPath9()
    {
        $this->__load();
        return parent::getWebPath9();
    }

    public function preUpload9()
    {
        $this->__load();
        return parent::preUpload9();
    }

    public function upload9()
    {
        $this->__load();
        return parent::upload9();
    }

    public function removeUpload9()
    {
        $this->__load();
        return parent::removeUpload9();
    }

    public function getAbsolutePath10()
    {
        $this->__load();
        return parent::getAbsolutePath10();
    }

    public function getWebPath10()
    {
        $this->__load();
        return parent::getWebPath10();
    }

    public function preUpload10()
    {
        $this->__load();
        return parent::preUpload10();
    }

    public function upload10()
    {
        $this->__load();
        return parent::upload10();
    }

    public function removeUpload10()
    {
        $this->__load();
        return parent::removeUpload10();
    }

    public function setPath1($path1)
    {
        $this->__load();
        return parent::setPath1($path1);
    }

    public function getPath1()
    {
        $this->__load();
        return parent::getPath1();
    }

    public function setPath2($path2)
    {
        $this->__load();
        return parent::setPath2($path2);
    }

    public function getPath2()
    {
        $this->__load();
        return parent::getPath2();
    }

    public function setPath3($path3)
    {
        $this->__load();
        return parent::setPath3($path3);
    }

    public function getPath3()
    {
        $this->__load();
        return parent::getPath3();
    }

    public function setPath4($path4)
    {
        $this->__load();
        return parent::setPath4($path4);
    }

    public function getPath4()
    {
        $this->__load();
        return parent::getPath4();
    }

    public function setPath5($path5)
    {
        $this->__load();
        return parent::setPath5($path5);
    }

    public function getPath5()
    {
        $this->__load();
        return parent::getPath5();
    }

    public function setPath6($path6)
    {
        $this->__load();
        return parent::setPath6($path6);
    }

    public function getPath6()
    {
        $this->__load();
        return parent::getPath6();
    }

    public function setPath7($path7)
    {
        $this->__load();
        return parent::setPath7($path7);
    }

    public function getPath7()
    {
        $this->__load();
        return parent::getPath7();
    }

    public function setPath8($path8)
    {
        $this->__load();
        return parent::setPath8($path8);
    }

    public function getPath8()
    {
        $this->__load();
        return parent::getPath8();
    }

    public function setPath9($path9)
    {
        $this->__load();
        return parent::setPath9($path9);
    }

    public function getPath9()
    {
        $this->__load();
        return parent::getPath9();
    }

    public function setPath10($path10)
    {
        $this->__load();
        return parent::setPath10($path10);
    }

    public function getPath10()
    {
        $this->__load();
        return parent::getPath10();
    }

    public function addKomentarze(\Informacje\Main\MainBundle\Entity\Komentarz $komentarze)
    {
        $this->__load();
        return parent::addKomentarze($komentarze);
    }

    public function removeKomentarze(\Informacje\Main\MainBundle\Entity\Komentarz $komentarze)
    {
        $this->__load();
        return parent::removeKomentarze($komentarze);
    }

    public function getKomentarze()
    {
        $this->__load();
        return parent::getKomentarze();
    }

    public function addPopularity(\Informacje\Main\MainBundle\Entity\Popularity $popularity)
    {
        $this->__load();
        return parent::addPopularity($popularity);
    }

    public function removePopularity(\Informacje\Main\MainBundle\Entity\Popularity $popularity)
    {
        $this->__load();
        return parent::removePopularity($popularity);
    }

    public function getPopularity()
    {
        $this->__load();
        return parent::getPopularity();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'header1', 'header2', 'header3', 'content', 'description1', 'description2', 'description3', 'description4', 'description5', 'description6', 'description7', 'description8', 'description9', 'description10', 'rodzaj', 'czas', 'path1', 'path2', 'path3', 'path4', 'path5', 'path6', 'path7', 'path8', 'path9', 'path10', 'popularity', 'komentarze');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}